apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ziralink-ids.fullname" . }}
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.environmentVariables.environment }}"
  ZIRALINK_CONNECTIONSTRINGS_DB: "{{ .Values.environmentVariables.connectionStrings.db }}"
  ZIRALINK_API_URL: "{{ .Values.environmentVariables.apiUrl }}"
  ZIRALINK_CLIENT_URL: "{{ .Values.environmentVariables.clientUrl }}"
  ASPNETCORE_URLS: "{{ .Values.environmentVariables.aspNetCoreUrls }}"
  ASPNETCORE_Kestrel__Certificates__Default__Password: "{{ .Values.environmentVariables.certificatePassword }}"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "{{ .Values.environmentVariables.certificatePath }}"